### ISSUE TITLE
 mask to RLE

### ISSUE THREAD

**Issue by shangsichang** [asehmi/streamlit-label-studio-frontend#10]
I want to know what is the encoding format of RLE when converting mask to RLE in Label Studio. My own test is very strange.

![image](https://github.com/user-attachments/assets/99150754-27b9-4650-b718-ca667463f691)

**Comment by asehmi** [comment]
This is a question for Label Studio developer forum. I have no association with LS. Thanks.

**Comment by shangsichang** [comment]
> This is a question for Label Studio developer forum. I have no association with LS. Thanks.

Alright, thank you very much.
