### ISSUE TITLE
Can we work on local images ?

### ISSUE THREAD

**Issue by pabloovitale** [asehmi/streamlit-label-studio-frontend#2]
My task file looks like this :

```
[
    {
        "data": {
            "id_doc":"1",
            "image": "/home/path_to_img/image.jpg"
        }
    },
    {
        "data": {
            "id_doc":"2",
            "image": "/home/path_to_img/image2.jpg"
        }
    }
]
```
I receive this error message :

**There was an issue loading URL from $image value

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)**

Can i have further details on this ? I don't understand how i can upload local images ?

Thank you

**Comment by asehmi** [comment]
I've updated the code to Streamlit>=1.18.0 and added a note in the readme about using local images, and also provided an additional config example in the app to annotate a local image.

**Comment by pabloovitale** [comment]
Thank you a lot ! I'll try this

**Comment by shyam573** [comment]
Can you give an example to load multiple local images? It doesn't seem seem to work at the moment. Thanks in advance.
