### ISSUE TITLE
Part of UI is missing

### ISSUE THREAD

**Issue by janezlapajne** [asehmi/streamlit-label-studio-frontend#3]
Hello, I am trying to integrate label-studio into my own streamlit app. However, when I integrate the app only part of the UI is shown. Also, if I go to the streamlit app provided (https://label-studio-frontend.streamlit.app/) there is also a part missing. Is there any quick fix available? Thanks!

**Comment by asehmi** [comment]
If you're talking about the blank grey space below the annotation area, that's controlled by the viewport height. I have a setting for that in the sidebar. Re-open an issue if this is not the case, and please attach a screenshot of what you mean.

Cheers.

**Comment by janezlapajne** [comment]
No, I am talking about the screen space the app occupies. Only half of the screen is used for the UI, see: https://prnt.sc/EC6Nfj56NF7j  

In essence, if the sidebar on the left is seen, the UI is cut.

**Comment by asehmi** [comment]
There's nothing missing in the UI, I've just divided the main area into two columns and am rendering the LSF component in the left column. See: https://github.com/asehmi/streamlit-label-studio-frontend/blob/0b739d74c6e357353ad2ff6bf409fff10b9e7f1f/app.py#L316

Feel free to adjust the dims or remove the columns completely. (I have a super wide screen and this layout suited me.)

**Comment by janezlapajne** [comment]
Ah, ok, that makes sense :)
Thanks, I will do that!
