### ISSUE TITLE
How to upgrade the label studio version from 1.4.0?

### ISSUE THREAD

**Issue by shyam573** [asehmi/streamlit-label-studio-frontend#4]
Thanks for the wonderful code. Upgrading the label studio from 1.4.0 to the latest does not load the tool. Is there a way to upgrade it to the latest version?

**Comment by asehmi** [comment]
Hi - I don't do any work with annotations, so haven't looked at the developments in LSF over the past year or so. As an official Streamlit "Creator" (their term for an MVP), I built this solution only as an example to help the Streamlit dev community understand how to use static HTML components to embed fairly complex third party solutions.

I'll have to spend some time looking at this, but can't promise when. I see LSF is now at 1.8 and I'm using 1.4 so there may be some subtle issues to overcome.

Have you tried to step through the LSF code in the browser dev tools yourself, or looked at the dev web console and noticed any obvious errors or missing JS files that the new version is looking for? Perhaps the CSS is different too.

See the latest LSF repo here for some inspiration, and if you do find the issue and fix it, please submit a PR :)

https://github.com/HumanSignal/label-studio-frontend
