### ISSUE TITLE
how to relate my own button of streamlit to Submit of label-studio

### ISSUE THREAD

**Issue by qzlshy** [asehmi/streamlit-label-studio-frontend#6]
I want to add a button use streamlit to save annotation and change to next image with out click Submit button of label-studio. what can I do?

**Comment by asehmi** [comment]
I guess you could add a button in the Streamlit app which, on-click, uses JavaScript to invoke the click action in the Label Studio Frontend app. There are a couple of JS Streamlit packages about. I wrote a gist that you can refer to here: https://gist.github.com/asehmi/a1e9bb139c96e4bcffea3d12c4d5c0c4
