### ISSUE TITLE
The view is cutoff

### ISSUE THREAD

**Issue by sammycoxman** [asehmi/streamlit-label-studio-frontend#7]
This is really great code. However, one thing that is quite frustrating is the view is cutoff for a lot of your examples when I load the app from https://label-studio-frontend.streamlit.app/ . It would be nice if the text message "Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, .." spanned across the page

<img width="1671" alt="image" src="https://github.com/asehmi/streamlit-label-studio-frontend/assets/135861288/0645c59b-94e6-4f24-a87b-bd34174baea6">

**Comment by asehmi** [comment]
Hi - simply run the app with a different column config on this line: https://github.com/asehmi/streamlit-label-studio-frontend/blob/0b739d74c6e357353ad2ff6bf409fff10b9e7f1f/app.py#L316C32-L317C5. The config I use fits fine on my wide screen. One could also interrogate the screen width using JavaScript before setting the columns, but...
