### ISSUE TITLE
more than twelve annotations

### ISSUE THREAD

**Issue by shangsichang** [asehmi/streamlit-label-studio-frontend#9]
When I have more than twelve annotations, the page does not display properly. How should I adjust it?
![微信图片_20240717125654](https://github.com/user-attachments/assets/edd53184-ce81-4e71-9e6b-cc54d267e148)

![Uploading 微信图片_20240717125707.png…]()

**Comment by asehmi** [comment]
Have you tried adjusting the viewport height settings in the sidebar?

P.S. this app is an example for developers, so feel free to go and mess with code. If you implement any new and useful features, send me a PR.

**Comment by shangsichang** [comment]
Thank you very much, I have solved my problem using your suggestion.
